name = "Lean4270"
version = "0.1.0"
defaultTargets = ["Lean4270"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"

[[lean_lib]]
name = "Lean4270"
